### ISSUE TITLE
mbed-drivers/app.h should be relocated to core-util

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/mbed-drivers#118] opened 2015-11-18 13:00 UTC
Using the header app.h should not require bringing in all of mbed-drivers. In particular, app.h is needed by the POSIX port of Minar, which needs to remain clear of mbed-drivers.

**Comment by 0xc0170** [comment] 2015-11-18 13:19
True , declaration should be elsewhere (core-util), definition for mbed will be here.

**Comment by autopulated** [comment] 2015-11-19 10:43
I don't think it necessarily should be moved – using `minar` doesn't imply that you're using app_start. The logic associated with replacing main with app_start is contained in this module, so if you define app_start without including mbed-drivers it won't work.

**Comment by rgrover** [comment] 2015-11-19 13:13
Can we then extract the retarget mechanism into its own module?
POSIX can provide its own retarget.cpp, but it can't afford to pull mbed-drivers.

**Comment by autopulated** [comment] 2015-11-19 13:42
_Should_ non-mbed OS programs use `app_start` at all though? That's the mbed OS entry point.

**Comment by ciarmcom** [comment] 2015-11-19 14:43
ARM Internal Ref: IOTSFW-1281

**Comment by rgrover** [comment] 2015-11-19 15:02
@autopulated are we defining non-mbed-drivers as non-mbed OS?

**Comment by autopulated** [comment] 2015-11-19 16:00
I would think so?

**Comment by rgrover** [comment] 2015-11-19 16:22
MINAR based applications can be run usefully under POSIX, and that doesn't require mbed-drivers. And mbed-drivers need not have a port for all platforms where we wish to run mbed OS.

**Comment by bogdanm** [comment] 2015-11-23 14:06
I tend to agree with @rgrover, mostly because it keeps things simple for us: if we want to run MINAR tests under POSIX, for example, we want them to start with `app_start` instead of `main`, so we can keep the code simple. At this point, I don't see why we'd need to break the `app_start` rule for POSIX.

**Comment by bremoran** [comment] 2015-11-23 14:13
It's trivial to define a main that schedules ```app_start```. That said, the code is effectively common to all minar-based applications, which is the reason for ```app_start``` in the first place. If ```app.h``` is going to move, should it move into minar?

**Comment by autopulated** [comment] 2015-11-23 14:14
if it's just a matter of tests, it should be the test framework that provides a consistent API though, should it not?

On posix you could reasonably want to use minar in a single thread of your application: if MINAR pulls in a library that defines main, that becomes very hard to do.

**Comment by bogdanm** [comment] 2015-11-24 09:27
It's not about a consistent API of the test framework, it's about having the same point (`app_start`) in boht mbed OS and POSIX, as opposed to having `app_start` in mbed OS and `main` in POSIX. I don't think threading is an issue right now.

**Comment by autopulated** [comment] 2015-11-24 09:45
You're thinking about it backwards though: the module that defines app_start **by definition** must implement main.

The question is really: "should `main` be implemented in mbed-drivers, or should `main` be implemented in core-util".

**Comment by bogdanm** [comment] 2015-11-24 11:00
> should main be implemented in mbed-drivers, or should main be implemented in core-util

What about `minar`? Since, after all, the current version of `main` is particular to `minar`.

**Comment by autopulated** [comment] 2015-11-24 11:10
Yes, because mbed OS (mbed-drivers) uses MINAR in a particular way (i.e. in the main thread).

you don't need a function called app_start to use minar, you just need to start the scheduler somewhere.

**Comment by jrobeson** [comment] 2015-12-05 04:02
glib's event loops allows me to use main() as normal, I would expect minar to be the same.

**Comment by hugovincent** [comment] 2015-12-14 13:05
@autopulated @bogdanm I'd have thought putting it in `minar` makes the most sense.

**Comment by autopulated** [comment] 2015-12-14 15:48
@hugovincent OK, but on the understanding that it requires minar to override main, making it difficult to use minar without completely restructuring an existing application (for example it'd be hard to use in a single thread alongside other things in a user-mode program on Linux/ an RTOS).

**Comment by hugovincent** [comment] 2015-12-14 15:57
What about `minar-platform-mbed`?

**Comment by autopulated** [comment] 2015-12-14 15:58
That would be better, but a bit confusing I think – if it's there, why not leave it in mbed-drivers, since that module has a dependency on mbed-drivers?

**Comment by bogdanm** [comment] 2015-12-18 11:41
I vote for moving `app.h` into `minar`, but keeping the implementation of `main` in `mbed-drivers`. For POSIX, we can implement `main` in `minar-platform-posix`, which is actually the case right now.
I want to move this forward (since it is needed for MINAR tests), so if I don't get any strong oppinions against this in the next 2 hours, or if I'll get +1s before that, I'll make it happen.

**Comment by autopulated** [comment] 2015-12-18 13:13
I still think that's the wrong thing to do. app_start is an mbed_os API, not a minar API. You don't need to use app_start to test/use minar.

**Comment by bogdanm** [comment] 2015-12-18 13:16
> You don't need to use app_start to test/use minar.

I'd be totally for that, if all the tests that we have in MINAR wouldn't use `app_start` already, which feels quite natural to me. What would you do instead?

**Comment by autopulated** [comment] 2015-12-18 13:21
Well what's missing is a consistent way of writing tests: something which abstracts app_start (or just provides it) on posix: adding a separate testDependency module which implements main and provides app_start which could be used on posix would be fine I think.

**Comment by bogdanm** [comment] 2015-12-18 15:39
OK, that makes sense. `minar-platform-posix` already has a main, so it could also define `app-start`. It's not as clean as what you suggested (testDependency), but it'd probably work.

**Comment by bogdanm** [comment] 2015-12-21 18:29
Turns out that adding the definition of `app_start` into `minar-platform-posix` solves the problem only partially. If I try to break `core-util`'s dependency on `mbed-drivers` by moving the test environment into a separate repository, the dependency still needs to exist, since the definition of `app_start` currently lives in `mbed-drivers` (and of course `core-util` needs that definition for its tests). So either:

1. we move the definition of `app_start` into `core-util`, as originally proposed
2. we create another repository that contains the definition of `app_start` alone

I vote for 1, since 2 feels a bit too much.

**Comment by bremoran** [comment] 2015-12-21 18:45
That implies a dependency of core util on minar. That seems wrong, since minar is a consumer of core util. App start belongs in minar.

**Comment by bogdanm** [comment] 2015-12-21 18:49
That might be better indeed, since moving `app_start` alone is not enough, one also needs to move the `app_start` specific implementation of `main` out of `mbed-drivers`. `minar` does look like a good place for both of these, especially `minar` is the reason why we use `app_start` instead of `main` in mbed OS.

**Comment by hugovincent** [comment] 2015-12-21 22:31
@bogdanm true, but @autopulated made a good point above: putting `main` in `minar` itself complicates use of `minar` on POSIX or any non-mbed OS environment.

**Comment by bogdanm** [comment] 2015-12-22 09:46
@hugovincent, point taken, but this feels like we're worrying way too much about a bridge that we don't have to cross yet. In any case, do you (or anybody else) have a suggestion for a more elegant fix? What about this: we create a separate module (`mbed-app-start` ?) that contains both the definition of `app_start` and the mbed OS specific implementation of `main`. That module can be used both as a regular dependency (by `mbed-drivers` for example) or as a test dependency (when testing (say) `core-util` on POSIX). Would this work for you?

**Comment by autopulated** [comment] 2015-12-22 10:42
Sounds like core-util should have a testDependency on the implementation of main in mbed-drivers.

Note that you can easily reproduce the _declaration_ of app_start which is currently in `mbed-drivers/app.h`, if splitting that into a separate module seems unreasonable.

It also seems reasonable to me to have multiple implementations of main that do the same thing on different platforms: I don't see why you'd expect the mbed-os main-calls-app-start implementation to be the same as a posix equivalent (the mbed OS one possibly has to do some things the posix one doesn't, and visa versa).

**Comment by bogdanm** [comment] 2015-12-22 10:47
I don't think I understand your proposed solution here.

**Comment by autopulated** [comment] 2015-12-22 11:02
3. Write a new module that declares app_start and implements main() calling it, which is only used as a testTargetDependency when running on posix.

core-util should have a testTargetDependency on mbed-drivers

At some point in the future, our test framework grows to provide cross-platform abstraction of start/main, and modules have a testDependency on that, instead of on the implementation of main directly.

**Comment by bogdanm** [comment] 2015-12-22 11:05
> core-util should have a testTargetDependency on mbed-drivers

That's precisely what we're trying to avoid: a dependency on `mbed-drivers` for `core-util` or any other module that we want to be able to test in a POSIX environment. `mbed-drivers` doesn't plya nice on POSIX.

**Comment by autopulated** [comment] 2015-12-22 11:07
test**Target**Dependency

**Comment by bogdanm** [comment] 2015-12-22 11:11
OK, but you still need a place (a test target dependency) where you define `main` for Linux. Or would you rather define `main` separately in each module that needs to be testable in Linux?

**Comment by autopulated** [comment] 2015-12-22 11:14
> (3) Write a new module that declares app_start and implements main() calling it, which is only used as a testTargetDependency when running on posix.

**Comment by bogdanm** [comment] 2015-12-22 11:15
Sorry, I completely missed that initially. OK, I think we can do that.

**Comment by autopulated** [comment] 2015-12-22 12:07
no problem ;)

**Comment by bogdanm** [comment] 2016-01-19 11:11
Fixed by #137

**Closed by bogdanm** 2016-01-19 11:11 UTC
Labels: mirrored
